### PR TITLE
Fix Tag related bugs

### LINKED ISSUE #160: [PE-D][Tester B] :list t/friend matches `Friend` as well, even though tags are documented as case-sensitive
Environment:
- App version: v1.5.1
- OS: Windows 11
- Java: 17

Steps to reproduce:
1. Enter `:clear` and then `yes`.
2. Enter `:add n/Ada Lovelace p/91234567 e/ada@example.com a/NUS Computing t/friend`.
3. Enter `:add n/Grace Hopper p/82345678 e/grace@example.com a/COM2 t/Friend`.
4. Enter `:tags` to confirm that both `friend` and `Friend` exist as separate tags.
5. Enter `:list t/friend`.

Expected:
Only the contact tagged `friend` should be shown, since the UG states that tags are case-sensitive and specifically says `friend` and `Friend` are treated as distinct tags.

Actual:
Contacts tagged `Friend` are also shown.

Why this is a bug:
The app itself treats those tags as distinct in `:tags`, but the filtering behavior merges them. This makes it impossible to search for one case-distinct tag without also matching the other.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #175: [PE-D][Tester A] `:list` is not case-sensitive when listing by tag
In the user guide, it is stated that:

Image

It is expected that since `friend` and `Friend` are treated as separate tags, `:list t/friend` and `:list t/Friend` should only show persons with the relevant case-sensitive tag. However, it seems that the current implementation is case-insensitive and both `friend` and `Friend` are treated as the same tag for listing purposes.

Steps to recreate:

1. Add a person with tag `friend`.  `:add n/John Doe e/john@email.com p/91234567 a/Block 123 t/friend`

Image

2. Add another person with tag `Friend`. `:add n/Alice e/alice@email.com p/91224567 a/Block 456 t/Friend`

Image

3. List with tag modifier `friend`. `:list t/friend`

Image

Expected behavior: Only `John Doe` should be shown, as his tag is `friend` while `Alice` has `Friend`.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #178: [PE-D][Tester D] [Logic] Application allows a contact to have more than 10 tags, violating S-02
#### Overview
Requirement **S-02** states that any single contact should have "up to 10 tags." However, the system allows the addition of 11 or more tags to a single contact without error.

#### Steps to Reproduce
1. Launch 0rb1t.
2. Add a contact with 11 tags: 
   `:add n/Test p/98765432 e/t@t.com a/a t/1 t/2 t/3 t/4 t/5 t/6 t/7 t/8 t/9 t/10 t/11`
3. View the contact in the sidebar or Details Panel.

#### Expected Result
The system should reject the command with an error: "A contact cannot have more than 10 tags (S-02 constraint)."

#### Actual Result
The contact is created with all 11 tags. This violates the documented Scalability Requirements and can lead to UI layout breakage in the sidebar.

#### Environment
- Version: v1.5 (0rb1t)

#### Evidence
Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #185: [PE-D][Tester B] :tags does not display mixed-case tags in human-friendly alphabetical order
Environment:
- App version: v1.5.1
- OS: Windows 11
- Java: 17

Steps to reproduce:
1. Enter `:clear`.
2. Enter `yes`.
3. Enter `:add n/Ada p/91234567 e/ada@example.com a/NUS t/apple`.
4. Enter `:add n/Grace p/82345678 e/grace@example.com a/COM2 t/Banana`.
5. Enter `:tags`.

Expected:
The tags should be displayed in a human-friendly alphabetical order, e.g. `apple, Banana`.

Actual:
The tags are displayed as `Banana, apple`.

Why this is a bug:
The UG says tags are displayed in alphabetical order. Using raw case-sensitive string ordering produces an ordering that does not match normal user expectations for alphabetical display.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### LINKED ISSUE #206: Constraint Tags to 32 characters
update ug as well

### PR DESCRIPTION
**Pull request by Jaepple**
Summary

- Fix inconsistent tag casing by normalizing tags to lowercase at creation time. Tags added through :add or :edit are now automatically stored in lowercase, which keeps tags listing consistent.
- Enforce constraint of 10 tags per contact.
- Enforce 32 character count for each tag.
- Update the UG to account for all of these changes.

Closes #160 
Closes #185 
Closes #178 
Closes #175 
Closes #206

### CODE REVIEW

File: src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java [hunk 1]
```diff
@@ -27,6 +28,7 @@ public class JsonAdaptedPersonTest {
     private static final String INVALID_ADDRESS = " ";
     private static final String INVALID_EMAIL = "example.com";
     private static final String INVALID_TAG = "#friend";
+    private static final String TOO_LONG_TAG = "a".repeat(33);
```
Comment (kavishsathia) [inline src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java:31]: Consider moving this to a constant.
