### PR TITLE
Remove Sidebar Refresh on Edit

### LINKED ISSUE #108: UX Issue: Inconsistent filter reset across mutating commands
When I edit a person, the filter for the list reset, but when I favourite them, the filter doesn't reset.

### LINKED ISSUE #153: [PE-D][Tester B] :edit on a filtered list resets the contact list to show all contacts again
Environment:
- App version: v1.5.1
- OS: Windows 11
- Java: 17

Precondition:
- Launch the app with the default sample data.

Steps to reproduce:
1. Enter `:list n/alex`.
2. Confirm that only the matching contact is shown.
3. Enter `:edit 1 p/91234567`.
4. Observe the contact list after the edit succeeds.

Expected:
The filtered list should remain active until the user explicitly changes it, so that index-based follow-up actions still apply to the narrowed result set.

Actual:
After the edit, the app resets the list to show all contacts again.

Why this is a bug:
This makes index-based workflows error-prone. It is especially misleading because the UG itself suggests a workflow of narrowing the list first and then chaining index-based commands afterwards.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #181: [PE-D][Tester D] [Logic] Filtered and Sorted list context is lost after executing an :edit command
#### Overview
When a user has a filtered or sorted list visible, performing an `:edit` command causes the UI to reset to the default, unfiltered, and unsorted view. This violates the "Vim-like UI Consistency" requirement.

#### Steps to Reproduce
1. Filter for a specific tag: `:list t/friends`
2. Edit the contact at index 1: `:edit 1 p/88887777`
3. Observe the Sidebar List.

#### Expected Result
The sidebar should remain filtered for `t/friend` so the user can continue working within that context.

#### Actual Result
The list immediately resets to show all contacts. The user is forced to re-type the filter command after every single edit operation.

#### Environment
- Version: v1.5 (0rb1t)

#### Evidence
Currently filtered list:
Image

After running the `:edit 1 p/88887777` command:
Image

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by kavishsathia**
Closes #108, closes #153, closes #181

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/EditCommandTest.java [hunk 1]
```diff
@@ -95,6 +95,7 @@ public void execute_filteredList_success() {
         String expectedMessage = String.format(EditCommand.MESSAGE_EDIT_PERSON_SUCCESS, Messages.format(editedPerson));
 
         Model expectedModel = new ModelManager(new AddressBook(model.getAddressBook()), new UserPrefs());
+        showPersonAtIndex(expectedModel, INDEX_FIRST_PERSON);
```
Comment (Jaepple) [inline src/test/java/seedu/address/logic/commands/EditCommandTest.java:98]: LGTM! such an efficient fix!

**Review by Jaepple — COMMENTED** [review]
Looks great!
